import React from 'react';
import './Content.scss';

const Content = () => {
    return(
        <article>
            <b>Lorem ipsum dolor</b> <br/><br/>
            sit amet, consectetur adipiscing elit. In vitae magna eu dui eleifend venenatis. Aenean in eros ultricies, cursus eros sit amet, bibendum ex. Curabitur id commodo ex. Etiam blandit lorem metus, a dignissim nibh auctor ut. Aliquam eget sapien venenatis est dictum cursus sed at neque. Donec ullamcorper at libero et luctus. Phasellus eget lacus sit amet nulla dapibus congue vel sollicitudin purus. Aliquam eu facilisis lorem.
            Suspendisse molestie semper dolor sit amet fringilla. Duis eu turpis pharetra, pharetra sem vel, condimentum velit. Etiam pulvinar aliquam nisl, sed aliquet orci tempor ac. Duis ultricies massa iaculis dolor vehicula laoreet. Aenean vestibulum in lacus ac ultricies. Suspendisse congue egestas magna non rhoncus. Sed lobortis urna eu ex eleifend egestas. Pellentesque a feugiat urna, sit amet rutrum arcu. Vivamus consectetur in libero nec volutpat. Ut ultrices gravida blandit. Maecenas blandit urna quis lectus egestas pellentesque.
            Fusce et euismod neque, ut sodales neque. Aliquam eget orci lacus. Donec rhoncus lectus ac sem viverra suscipit. Nunc ultricies fringilla sem, vitae aliquet justo sollicitudin sed. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras pulvinar purus lacus. Duis id malesuada lorem. Pellentesque vehicula porta dolor at malesuada. In elit elit, sagittis eu leo non, mollis tincidunt libero. In malesuada risus ex, fringilla finibus ligula scelerisque at. Suspendisse euismod cursus vulputate. Praesent iaculis, massa rhoncus dignissim bibendum, elit tortor rhoncus sapien, eget rutrum lorem augue non neque. Nam sit amet diam eu lacus porta scelerisque. Sed eget massa vitae dolor accumsan scelerisque. Mauris eget mollis sem.
            Quisque eget enim tempor, consectetur ipsum sit amet, congue mi. Mauris vitae enim dictum, scelerisque felis ac, tempus purus. Donec ac lacus at sem volutpat ornare laoreet non sapien. In consectetur, felis sit amet eleifend aliquet, ipsum quam pulvinar elit, ultricies tempor mi risus eleifend tellus. Aliquam finibus arcu maximus aliquam consequat. Morbi accumsan congue ipsum vel laoreet. Proin hendrerit vel tellus non fringilla. Sed accumsan quam quis elementum tempus. Mauris bibendum mauris vel felis tristique bibendum. Cras nisi elit, venenatis a porta in, iaculis sed justo. Maecenas varius, libero eu imperdiet sollicitudin, tortor lacus ornare augue, sed maximus mauris mauris sed ligula. Etiam at consectetur magna.
            Morbi elementum risus quis eleifend varius. Nulla finibus et risus eget convallis. Nam mattis est nec dolor tempor facilisis. Quisque vitae libero gravida, molestie ex eu, iaculis felis. Etiam dictum at nunc quis laoreet. Praesent sit amet scelerisque magna. Nam viverra pretium neque, eu varius magna aliquam nec. Pellentesque non turpis interdum, imperdiet lectus ut, bibendum metus. Curabitur eleifend elementum enim, a malesuada neque tincidunt mattis. Etiam ultrices massa eget libero porta, non condimentum quam tincidunt. Pellentesque a suscipit magna. Sed vitae elit eu urna varius vulputate. Nulla sodales, purus cursus tristique condimentum, risus turpis dapibus nunc, et bibendum turpis nulla eu ipsum. Ut in lorem ut metus vehicula auctor eu vel nisl. Proin tempus nec nisi vel tincidunt.
            Phasellus et purus vitae mauris pretium pellentesque eu a quam. Morbi vulputate ipsum vitae elementum venenatis. Mauris dui diam, dictum vel ante sit amet, sollicitudin blandit sem. Integer tempor mauris nec erat efficitur, ac placerat augue sagittis. Nulla augue orci, placerat at egestas sed, cursus sit amet enim. Phasellus volutpat elit nibh, et bibendum tellus dictum ac. Nam consectetur est ut eros tempor, at faucibus augue pharetra. Sed ac mollis augue, pulvinar vestibulum est. Nunc molestie mollis ante ut ultrices. Aenean malesuada tellus id mi interdum, sit amet vehicula augue rhoncus. Vestibulum maximus sagittis eros sit amet aliquet. Suspendisse dapibus enim elit, id placerat dolor pulvinar ac. Donec at tempus magna, vestibulum fermentum est.
            Nunc elementum nisl quis libero vehicula, in aliquet purus consectetur. Pellentesque convallis blandit libero at malesuada. Morbi id posuere quam, ut vehicula nunc. Morbi semper, purus id feugiat cursus, neque libero mollis mauris, eget ornare quam dui sit amet ligula. Phasellus ut purus blandit, efficitur sapien quis, pulvinar neque. Fusce elementum quis nisl a vestibulum. Aenean ultricies viverra pharetra. Nunc accumsan sed nibh vitae fermentum. Vestibulum vitae ultricies erat. Integer molestie sollicitudin sollicitudin. Praesent ac posuere diam, sit amet feugiat libero. Nunc turpis diam, suscipit a augue quis, bibendum eleifend odio.
            In hac habitasse platea dictumst. Nunc ex felis, dictum ac posuere vitae, vehicula at magna. Maecenas posuere ex in enim suscipit porta. Suspendisse odio neque, tincidunt non porta vel, rhoncus sit amet velit. Pellentesque sit amet sagittis nibh. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse potenti. Integer tempor pretium est, a feugiat lacus. Aliquam laoreet vitae urna sit amet viverra. Sed non turpis ac ante faucibus consequat. Etiam libero augue, euismod a egestas vel, tempus eleifend purus. Pellentesque et augue id elit finibus commodo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse blandit gravida nisl, vitae pretium eros venenatis in. Donec quis mauris at augue scelerisque ultrices at pellentesque nulla.
            In at tortor vel ligula mattis vehicula nec a tortor. Etiam eget dui sed ex efficitur suscipit. Phasellus et sollicitudin nisi, et tempus magna. Etiam urna sem, blandit sed ante a, ullamcorper pretium leo. Mauris egestas elit eu congue dictum. Cras scelerisque odio a vestibulum varius. In at finibus nibh. Aenean tincidunt massa sed congue vehicula. Vivamus nulla quam, aliquam id lectus sit amet, ornare semper magna.
            Pellentesque id tellus non mi mollis varius. In orci libero, sodales at dolor in, aliquet vestibulum leo. Nunc gravida tempus tellus ut auctor. Integer elementum sem sit amet leo tincidunt, sit amet accumsan ex laoreet. Nullam sollicitudin tortor ut neque scelerisque, sed faucibus felis aliquam. Proin sed ligula nisl. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam vestibulum dignissim mattis. Duis pretium purus vel accumsan maximus. Etiam vel tincidunt purus. Etiam ut ligula dolor. Sed pellentesque velit vel vehicula rutrum. Mauris vitae nulla vel arcu viverra viverra eu at libero. Integer nec eleifend nibh, eget lacinia sapien. Praesent vel mi fringilla, rutrum massa a, faucibus tortor. Suspendisse potenti.
        </article>
    );
}

export default Content;